(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
SetOptions[EvaluationNotebook[],AutoGeneratedPackage->Automatic]


(* ::Input::Initialization:: *)
mpEuclideanQCoefficients[{m_,n_}] := Module[{r,q,i,j},
	i=0;
	r[-1]=n; 
	r[0] = m;
	While[r[i] > 0  , 
		q[i] = Floor[r[i-1]/r[i]];
		r[i+1] = r[i-1] - q[i]*r[i];
		i++;
	];
 Table[q[j],{j,0,i-1}]
];

mpEuclideanMatrixProduct[mn_] := Module[{q,res,eMatrix,sMatrix},
eMatrix = ({
 {1, 1},
 {0, 1}
});sMatrix=({
 {0, 1},
 {1, 0}
});
q = mpEuclideanQCoefficients[mn];
res= (Map[  MatrixPower[eMatrix,#] . sMatrix &,q]);
res= If[Length[res]>0,Dot@@res,IdentityMatrix[2]];
res
];

mpWindingNumberPair[mn_] := Module[{m,n,u,v},
{{n,v},{m,u}}=mpEuclideanMatrixProduct[mn];
{u,v}
];

mpDelta[mn_]:= -1 * If[EvenQ[Length[mpEuclideanQCoefficients[mn]]],1,-1];




